name: PMD Static Code Analysis + Conviso Platform
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  pmd-scan:
    name: PMD Static Code Analysis
    permissions:
      security-events: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'ruleset.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file to Github Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
      - name: Upload SARIF Results
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report.sarif
          path: pmd-report.sarif
  import:
    name: Import SARIF results to Conviso Platform 
    needs: pmd-scan
    runs-on: ubuntu-20.04
    container:
      image: convisoappsec/flowcli:latest
      env:
        FLOW_API_KEY: ${{secrets.CONVISO_API_KEY}}
        FLOW_PROJECT_CODE: ${{secrets.CONVISO_PROJECT_CODE}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download result from pmd scan
        uses: actions/download-artifact@v3
        with:
          name: pmd-report.sarif

      - name: SARIF Importation
        run: |
          conviso findings import-sarif --input-file pmd-report.sarif
